#! /bin/sh

# require:
#   $ brew install reattach-to-user-namespace

if [[ ( $OSTYPE == darwin* ) && ( -x $(which reattach-to-user-namespace 2>/dev/null) ) ]]; then
    tmux save-buffer /tmp/.tmux_to_pbcopy
    cat /tmp/.tmux_to_pbcopy | pbcopy

    # 下記は表示だけなのでなくてもOK
    HEAD=`head -1 /tmp/.tmux_to_pbcopy`
    TAIL=`tail -1 /tmp/.tmux_to_pbcopy`
    tmux display-message "Copy:  $HEAD  -  $TAIL"
fi
